### ISSUE TITLE
feat(markdown): add code formatting

### ISSUE THREAD

**Issue by insertish** [revoltchat/frontend#223]

**Comment by levabala** [comment]
should it be just importing the default prism dark css theme?
the same as with katex

**Comment by levabala** [comment]
@insertish

**Comment by eveeifyeve** [comment]
Markdown okay I could add prettier which would be better formater.

**Comment by eveeifyeve** [comment]
It seems like you already have prettier so is this solved?

**Comment by amycatgirl** [comment]
It's actually codeblock syntax highlighting. Frontend does not have Prism, so codeblocks will not have any type of syntax highlighting.

I was thinking if perhaps I could switch it to [Shiki](https://github.com/shikijs/shiki)

But I do have a fork that adds the feature, issue is that I have not updated any of my branches to the new UI.

**Comment by eveeifyeve** [comment]
I thought of switching to syntax highlighting with [solid-highlight](https://github.com/aidanaden/solid-highlight) because it's well known.

I have noticed that prism in frontend but thanks for mentioning it.

But I could make a fork with syntax highlighting quick that fixes the issue, only issue/concern is it going to affect page speed results or other rating's.

**Comment by legoraft** [comment]
Wouldn't [highlight.js](https://highlightjs.org/#usage) basically do the job? It also has an npm package and is quite fast

**Comment by insertish** [comment]
Another contender has entered the ring: https://shiki.style/
